### ISSUE TITLE
Wrong next hop used for tunnelled routes

### ISSUE THREAD

**Issue by plwhite** [projectcalico/calico-bird#3]
Consider the following case. There are three servers.

* A is a route reflector running BIRD
* B is a host running BIRD connected to A
* C is a host running BIRD connected to A.

If there is a route from C to D (in this example a Calico endpoint on C), then routes are advertised incorrectly.

B gets a route to D which goes via A's IP. This is a trivial bug in sysdep/linux/netlink which uses a.from rather than a.gw.

I have a fix and will submit it after testing.

**Comment by robbrockbank** [comment]
Fixed by #6
