### ISSUE TITLE
Documentation for build_routereflector is out of date for calicoctl 1.x

### ISSUE THREAD

**Issue by jdfless** [projectcalico/calico-bird#32]
The commands on https://github.com/projectcalico/bird/blob/v0.2.0/build_routereflector/README.md are incompatible with calicoctl 1.x, even though bird v0.2.0 is the official version in calico 2.x release from http://docs.projectcalico.org/v2.0/releases/.

**Comment by tmjd** [comment]
@jdfless Thank you for bringing this up.  I'm not sure when we will be able to update the doc.  We do welcome PRs if you are inclined to try updating it.

If you haven't seen them already, the follow docs should be able to help you to setup Router Reflectors and Calico to use them.
http://docs.projectcalico.org/v2.0/usage/configuration/bgp
http://docs.projectcalico.org/v2.0/usage/bird-rr-config

**Comment by robbrockbank** [comment]
I've removed the docs from this repo and moved (and updated) into the main projectcalico docs:

http://docs.projectcalico.org/master/usage/routereflector/calico-routereflector

Note that the routereflector container image is really only used within our ST framework so it has some major limitations.  However, it might prove a useful starting point if people are interested in building it out to make it more usable in a real deployment.
