### ISSUE TITLE
Investigate incorporating kumina/birdwatcher for exposing bird metrics via prometheus

### ISSUE THREAD

**Issue by bradbeam** [projectcalico/calico-bird#47]
I came across https://github.com/kumina/birdwatcher the other day while doing some research on calico and prometheus. Curious if it'd be worth the Calico team reaching out to Kumina to see if this can be incorporated with calico/bird out of the box.

**Comment by caseydavenport** [comment]
Looks like a neat project.  

My inclination would be not to package it within say calico/node, but instead just to make sure we've got consistent integration points such that it can easily be installed via a DaemonSet on any Calico cluster.

**Comment by caseydavenport** [comment]
I don't think there's anything for us to do on our side for this.
