### ISSUE TITLE
Merge with upstream projects ?

### ISSUE THREAD

**Issue by darkweaver87** [projectcalico/calico-bird#56]
Hello,

It's an open question :-)
I think it would be better to merge with upstream projects (by doing PR) because on long term view you won't benefit from the commits of people maintaining those projects and you'll eventually face merging conflicts.
You already forked bird, confd and etcd and I don't think creating other projects is necessary for the minor modifications/ additional features you made to make the glue around calico project.

Thanks :-)

Rémi

**Comment by caseydavenport** [comment]
@darkweaver87 as far as etcd goes, we've submitted a PR and we're waiting to see if it will be approved. We plan on going back to the upstream version ASAP :)

For confd, we've made substantial changes and I don't think it makes sense to try to merge them back upstream.

@neiljerram are you the right person to comment on the feasibility of merging bird with upstream?

**Comment by nelljerram** [comment]
> @neiljerram are you the right person to comment on the feasibility of merging bird with upstream?

@caseydavenport @darkweaver87 Yes, it is absolutely feasible for us to merge back with upstream bird, and I would love us to do that.  I raised that [on the BIRD mailing list](http://bird.network.cz/pipermail/bird-users/2016-September/010629.html) a while ago and got an encouraging response.  It's just that there's a little work needed that we haven't yet got round to.
