### ISSUE TITLE
bug in build.sh

### ISSUE THREAD

**Issue by npu21** [projectcalico/calico-bird#71]
for **get the correct TARGETARCH**,if the arch is x86_64 like this

> root@ubuntu:~# uname -m
x86_64
TARGETARCH will be x86_64, which should be amd64
## Expected Behavior
TARGETARCH x86_64
## Current Behavior
TARGETARCH amd64

**Comment by nelljerram** [comment]
@npu21 What is the higher-level problem here?  The value of `TARGETARCH` is not necessarily a problem, unless it has some further bad effect.
