### ISSUE TITLE
Docker image not found

### ISSUE THREAD

**Issue by RichardPhilRoy** [projectcalico/calico-bird#94]
Hi, I'm trying to install docker image of bird on ubuntu 18, but I'm getting this error
```
docker pull calico/bird
```

```
Using default tag: latest
Error response from daemon: manifest for calico/bird:latest not found: manifest unknown: manifest unknown
```

**Comment by caseydavenport** [comment]
@RichardPhilRoy this repo is used internally within Calico, and isn't meant to be installed standalone.
